
use_default_settings: true

general:
  instance_name: "Maoyue's SearXNG"
  contact_url: https://maoyue.tw/#contact

search:
  autocomplete: "duckduckgo"
  favicon_resolver: "duckduckgo"

server:
  base_url: https://search.maoyue.tw/
  image_proxy: true

ui:
  query_in_title: true

plugins:
  searx.plugins.infinite_scroll.SXNGPlugin:
    active: true
  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: true

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: true
  - name: startpage
    engine: startpage
    shortcut: sp
    disabled: true
    startpage_categ: web
    categories: [general, web]
    additional_tests:
      rosebud: *test_rosebud
